var Language = {
    Confirm:'确定',
    Cancel:'取消',
    Close:'关闭',
    MessageBoxTitle_01: '信息提示',
    MessageBoxTitle_02: '操作成功',
    MessageBoxTitle_03: '错误提示',
    MessageBoxTitle_04: '确认提示',
	TableTotal: '条记录',
	Total: '共',
	Page: '页',
	Prev: '上一页',
	Next: '下一页',
	StatusEnable: '正常',
	StatusDisable: '已停用',
	Message001: '“用户名 ”不能为空！',
	Message002: '“用户名”必须为英文字母或数字！',
	Message003: '“用户名 ”不能小于6个字符',
	Message004: '请为用户选择“部门”！',
	Message005: '请为用户选择“主角色”！',
	Message006: '“密码 ”不能为空！',
	Message007: '“密码”不能小于6个字符！',
	Message008: '两次输入的“密码”不一致！',
	Message009: '用户“姓名”不能为空！',
	Message010: '“重置密码”不能为空！',
	Message011: '“角色名称”不能为空！',
	Message012: '“当前密码”不能为空！',
	Message014: '“部门名称”不能为空！',
	Message015: '“系统名称”不能为空！',
	Message016: '“网站地址”不能为空！',
	Message017: '“页脚信息”不能为空！',
	Logout: '退&nbsp;&nbsp;出',
	LogoutMessage: '您真的要退出系统吗？',
	UserDelConfirm: '您真的要删除这个用户吗？删除后将不能恢复，请谨慎操作！',
	UploadTitle: '上传文件',
	UploadSuccess: '成功',
	NetdiskFilesTotal: '个文件 共计：',
	Root: '根目录',
	NewFolder: '新建文件夹',
	OpenFilesError001: '对不起，不能同时打开多个文件！',
	OpenFilesError002: '请选择需要打开的文件或文件夹！',
	DeleteFilesError002: '请选择需要删除的文件或文件夹！',
	DeleteFilesConfirm: '请注意，文件删除后不可恢复，真的要删除吗？ ',
	EmptyFolder:'文件夹内没有文件',
	FileName:'文件名：',
	Size:'大小：',
	Date:'修改日期：',
	ShareTitle:'分享下载链接',
	ShareText:'请复制以下分享链接：',
	CopyToClip:'复制到剪切板（仅支持IE浏览器）',
	CopyToClipSuccess:'已将链接复制到剪切板中',
	DownloadFilesError001: '对不起，不能同时下载多个文件！',
	DownloadFilesError002: '请选择需要下载的文件！',
	DownloadFilesError003: '对不起，暂不支持对文件夹的下载！',
	RoleDelConfirm: '您真的要删除这个角色吗？删除后将不能恢复，请谨慎操作！',
	DeptDelConfirm: '您真的要删除这个部门吗？删除后将不能恢复，请谨慎操作！',
	CopySuccess: '已复制到剪切板',
	ZoomIn:'放大图像',
	ZoomOut:'缩小图像',
	ZoomActual:'以实际大小显示',
	ZoomAuto:'自适应屏幕大小',
	PrevPic:'上一张图片',
	SlidePlay:'播放幻灯片演示',
	NextPic:'下一张图片',
	AutoPlay:'自动播放',
	Loading: '加载中...',
	loadError: '加载错误',
	FileTypeFolder: '文件夹',
	FileType: '文件',
	FileListTitleName: '名称',
	FileListTitleType: '类型',
	FileListTitleSize: '大小',
	FileListTitleDate: '修改时间',
	DiskFreeText: ' 可用&nbsp;&nbsp;&nbsp;&nbsp;共 ',
	PropertyTitle: '属性 ',
	PropertyType: '文件类型 ',
	PropertyPosition: '位置 ',
	PropertyCreateTime: '创建时间 ',
	PropertyModifyTime: '修改时间 ',
	PropertyReadTime: '最后访问',
	PropertyInclude: '包含',
	NothingRecord:'目前没有系统消息',
	Delete:'删除',
	Time:'时间',
	Day:'天',
	Hour:'小时',
	Min:'分钟',
	Just:'刚刚',
	Before:'前',
	ConfirmDeleteAllRecord:'您真的要删除所有记录吗？',
    Font: 'font-family: 微软雅黑, Microsoft Yahei, Hiragino Sans GB, tahoma, arial, 宋体;'
}